### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by FSbootcampP1G7** [FSbootcampP1G7/dnd-companion-app#6]
This task item is for tracking project proposal with due date of today 05/20/2024 if possible, or by end of class 05/21/2024

**Comment by FSbootcampP1G7** [comment]
TODO: add Dave Butterworth to task if necessary and decide Project and Required APIs ASAP for approval. Each member should suggest 2 PROJECT ideas and 2 SERVER-SIDE APIs so we have submission in by end class 05/21/2024.

https://coding-boot-camp.github.io/full-stack/apis/api-resources 
https://github.com/public-apis/public-apis

**Comment by FSbootcampP1G7** [comment]
Duffey-
Personalized Homepage:
-Google API
-Weather API

**Comment by FSbootcampP1G7** [comment]
Michael Smith:
Movie Buff Assistant - retrieve reviews and meta-data about favorite films.
Rotten Tomatoes API - https://developer.fandango.com/Rotten_Tomatoes 
Wikipedia API - https://www.mediawiki.org/wiki/API:Main_page

**Comment by FSbootcampP1G7** [comment]
Geri Koci :

Google Search API
Open Weather API - both of them are easy to use when coding in Javascript

**Comment by FSbootcampP1G7** [comment]
Cody Bogart

Google Search API - https://developers.google.com/custom-search/

Weather API - https://www.visualcrossing.com/weather-api?ga_api20&key=weather%20api&loc=9018751&gad_source=1&gclid=Cj0KCQjwjLGyBhCYARIsAPqTz1_xhWxQ5zxwe5kGUbMmqa8Xbx9aGI9b9hfNLpyDdpP5qVMnNdwk2uQaAnKPEALw_wcB

**Comment by Mtduffey36** [comment]
Project proposal was accepted. DnD companion website. closing this issue out
